// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwishBackend.StoreItems.Data;

#nullable disable

namespace SwishBackend.StoreItems.Migrations
{
    [DbContext(typeof(StoreItemsDbContext))]
    [Migration("20231206093456_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SwishBackend.StoreItems.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SwishBackend.StoreItems.Models.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            CategoryName = "Painting"
                        },
                        new
                        {
                            Id = new Guid("bb2ea796-c92a-4a02-8857-0763f7f4e80a"),
                            CategoryName = "Cars"
                        });
                });

            modelBuilder.Entity("SwishBackend.StoreItems.Models.Car", b =>
                {
                    b.HasBaseType("SwishBackend.StoreItems.Models.Product");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Car");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d037afe-1993-44f6-b46e-1617e39ee50c"),
                            Image = "car_image_1.jpg",
                            Name = "Car 1",
                            Price = 30000m,
                            ProductCategoryId = new Guid("bb2ea796-c92a-4a02-8857-0763f7f4e80a"),
                            Stock = 5,
                            Type = 1,
                            HorsePower = 200,
                            Model = "Model X"
                        },
                        new
                        {
                            Id = new Guid("31662f6f-dbab-4ef3-9f6f-2a8cb7cac813"),
                            Image = "car_image_2.jpg",
                            Name = "Car 2",
                            Price = 25000m,
                            ProductCategoryId = new Guid("bb2ea796-c92a-4a02-8857-0763f7f4e80a"),
                            Stock = 8,
                            Type = 1,
                            HorsePower = 150,
                            Model = "Model Y"
                        });
                });

            modelBuilder.Entity("SwishBackend.StoreItems.Models.Painting", b =>
                {
                    b.HasBaseType("SwishBackend.StoreItems.Models.Product");

                    b.Property<string>("PainterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Painting");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7861614d-4ce3-405c-9cc1-399158680d74"),
                            Image = "https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
                            Name = "Test Painging 1",
                            Price = 100m,
                            ProductCategoryId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            Stock = 10,
                            Type = 0,
                            PainterName = "Test 1"
                        },
                        new
                        {
                            Id = new Guid("936a4000-f78f-4095-82e3-300c7831a5d8"),
                            Image = "https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
                            Name = "Test Painging 2",
                            Price = 110m,
                            ProductCategoryId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            Stock = 16,
                            Type = 0,
                            PainterName = "Test 2"
                        },
                        new
                        {
                            Id = new Guid("907703df-5699-44c9-9c9c-ec6e25b5c59e"),
                            Image = "https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
                            Name = "Test Painging 3",
                            Price = 120m,
                            ProductCategoryId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            Stock = 12,
                            Type = 0,
                            PainterName = "Test 3"
                        },
                        new
                        {
                            Id = new Guid("c587af33-4262-4b28-bffe-b65ebd571b5b"),
                            Image = "https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
                            Name = "Test Painging 4",
                            Price = 100m,
                            ProductCategoryId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            Stock = 5,
                            Type = 0,
                            PainterName = "Test 4"
                        },
                        new
                        {
                            Id = new Guid("2404e29b-09e2-405a-a58b-2862ecb85e09"),
                            Image = "https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
                            Name = "Test Painging 5",
                            Price = 200m,
                            ProductCategoryId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            Stock = 12,
                            Type = 0,
                            PainterName = "Test 5"
                        },
                        new
                        {
                            Id = new Guid("a93a6587-04d8-4659-8971-5de664076b68"),
                            Image = "https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
                            Name = "Test Painging 6",
                            Price = 100m,
                            ProductCategoryId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            Stock = 10,
                            Type = 0,
                            PainterName = "Test 6"
                        });
                });

            modelBuilder.Entity("SwishBackend.StoreItems.Models.Product", b =>
                {
                    b.HasOne("SwishBackend.StoreItems.Models.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("SwishBackend.StoreItems.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
